rstudio/DT

- inst/htmlwidgets/lib/datatables/css/bootstrap/dataTables.extra.css
I don't know if the other classes ever come up, but I added all of the align/justify/nowrap options.
Here's a check:
```
ff <- tempfile(fileext = ".Rmd")
cat("```{r}
library(DT)
datatable(iris, style = 'bootstrap', class = c('compact'))\n```
" , file = ff)
rmarkdown::render(ff)
browseURL(gsub("Rmd", "html", ff))
```
> Add alignment bootstrap css to address #57

- R/shiny.R
Reverts rstudio/DT#84
I discovered a bug, one sec.
> Revert "Allow data frames to be used as renderDataTable values"

- R/shiny.R
Sorry, last time I had the final `quoted=TRUE` where it should've been `quoted=FALSE`.
> Allow data frames to be used as renderDataTable values

- R/datatables.R
- R/shiny.R
- man/dataTableOutput.Rd
This is a **straw man** proposal for how we could do this without requiring https://github.com/ramnathv/htmlwidgets/pull/122. It pulls in your no-register branch.
There are two hacks to point out, plus an open issue I think we should discuss.
Hack 1 is that the `preRenderHook` is evaluated and then removed in `widgetFunc`. This works fine but it feels like it definitely violates the spirit of `preRenderHook`. My first attempt tried to remove the preRenderHook altogether and copy that logic into the Shiny render function, but I couldn't figure out how to get the `escape` and `colnames` out. I thought that would be a pretty easy refactor for you, but I didn't want to go that far afield for this proof-of-concept.
Hack 2 is the usage of `currentSession` and `currentOutputName` variables, that …
> Simplify server handling

- R/datatables.R
- R/shiny.R
- man/dataTableOutput.Rd
- man/datatable.Rd
I know I said I was OK with us not doing this but I decided it was worth
it after all, for the following benefits:
1. Allows us to default server=TRUE when in a Shiny app
2. Allows server=TRUE to be specified identically whether datatable() or
data frame is returned in the renderDataTable expr
3. Prevents the nonsensical specification of server=TRUE when using DT
in a non-Shiny context
The code is actually quite a bit simpler than before I think, though
there is a nontrivial risk of regression.
> Move `server` parameter from datatable to renderDataTable

- inst/htmlwidgets/datatables.js
This fixes Tareef's ioslides issue. @jcheng5
> Defer the table render until the container has non-zero width/height

- inst/htmlwidgets/datatables.js
If we are in a flexdashboard mobile phone layout then we:
(a) Always want to use pagination (otherwise we'll have a "double scroll bar" effect on the phone); and
(b) Never want to fill the container (we want the pagination level to determine the size of the container)
> Always enable pagination in flexdashboard mobile layouts

- R/datatables.R
- inst/htmlwidgets/datatables.js
- man/datatable.Rd
This PR makes a couple of changes to sizing behavior aimed at making DT play better within notebooks and the viewer pane:
1. Explicit `width` and `height` values are no longer used in constructing the widget (unless the user passes them explicitly). Formerly, a default width of 100% and default height of "auto" were being used. These explicit values were subsequently foiling attempts to have DT fill all available space within the RStudio Viewer and in notebook mode. 
The sizing for Shiny was already being specified as width = "100%" and height = "auto", so it seems as if these widths and heights were being set for the benefit of knitr output. However, htmlwdiget sizing policies enable specification of knitr specific sizing behavior, so the following code should have the same effect:
```r …
```
> improvements to sizing behavior

- DESCRIPTION
- R/datatables.R
- R/shiny.R
- inst/htmlwidgets/css/datatables-crosstalk.css
- inst/htmlwidgets/datatables.js
- inst/htmlwidgets/datatables.yaml
Console example:
```r
devtools::install_github("jcheng5/d3scatter")
library(crosstalk)
library(DT)
library(d3scatter)
sd <- SharedData$new(iris)
bscols(
d3scatter(sd, ~Petal.Length, ~Petal.Width, ~Species, width = "100%"),
datatable(sd, width = "100%")
)
```
Shiny example (requires github version of leaflet):
```r
library(shiny)
library(crosstalk)
library(d3scatter)
library(leaflet)
library(DT)
options(shiny.launch.browser = TRUE)
d3scatterOutput("scatter", height = 250),
leafletOutput("map", height = 250),
selectInput("dataset", "Data set to show in table:", c("iris", "quakes"), "iris"),
DT::dataTableOutput("table", height = 250)
)
sd_iris <- SharedData$new(iris, group = "iris")
sd_quakes <- SharedData$new(quakes, group = …
```
> Crosstalk integration

- inst/htmlwidgets/datatables.js
This code isn't used anymore, and blows away any existing rowCallback.
> Remove rowCallback for Crosstalk

- inst/htmlwidgets/datatables.js
I had changed instance.ctselect to instance.ctselectHandle, but due to bad Find criteria I
missed some of the references. The effect of this bug was that selecting rows in the DT
would cause the same table to respond to the selection as if it was originating elsewhere,
so all but the selected rows would be hidden.
> Fix Crosstalk bug due to bad variable rename

- R/datatables.R
The JavaScript bindings are structured in such a way that Crosstalk
dependencies are always needed. This results in an extra ~19KB
(minified) JS dependency. We could definitely remove this dependency by
being more careful in the JS bindings not to touch crosstalk.* until a
group is passed in, but in the meantime this fixes fatal errors.
> Always include Crosstalk dependencies

- NEWS.md
- inst/htmlwidgets/datatables.js
> support shift+click to select mutiple rows

- R/shiny.R
This was left out when Crosstalk options were moved to `params` in https://github.com/rstudio/DT/commit/893708ca10def9cfe0733598019b62a8230fc52b
> Fix error checking when attempting to use Crosstalk in server mode

- inst/htmlwidgets/datatables.js
> support shift+click on server-process mode

- R/datatables.R
- inst/htmlwidgets/datatables.js
When I run roxygen all the rd files get rewritten so I didn't update docs
Feel free to disregard this PR if you have a different implementation.
Fixes #483
> add editable parameter

- inst/htmlwidgets/datatables.js
Currently, updateSearch ignores the regex settings. E.g. in the Shiny App below after a click on the button "search" we get an empty table.
Note: The fix isn't that nice as I simply copied some code from above. You might want to refactor it into a function. As I don't know much Javascript I didn't really want to try it myself.
```
library(shiny)
library(DT)
shinyApp(
DT::dataTableOutput("tbl"),
actionButton("but", "search")
),
output$tbl <- DT::renderDataTable(
data.frame(a = month.name, stringsAsFactors = FALSE),
options = list(search = list(regex = TRUE)),
filter = list(position = "bottom")
)
observeEvent(input$but, {
DT::updateSearch(DT::dataTableProxy("tbl"), keywords = list(columns = "Jan|Feb"))
})
}
)
```
> method updateSearch respects regex and case settings

- inst/examples/DT-crosstalk/plotly-persist.R
- inst/htmlwidgets/datatables.js
This adds the ability to perform persistent selection with plotly (similar to how https://github.com/rstudio/leaflet/pull/346 does for leaflet).
It would be ideal to have rows somehow reflect [plotly's selection color](https://github.com/rstudio/leaflet/pull/346/files#diff-8e0e6e242b99825df0596336e5ad4d7aR876), let me know if have any ideas how best to go about that (e.g. color the text or highlight the row?)
> Respond to plotly's persistent selection mode

- NEWS.md
- R/datatables.R
closes #511 
The fix #476 misses the fact that besides of column indexes, there're [4 kinds](https://datatables.net/reference/option/columnDefs.targets) of `columnDefs.targets` in total.
This PR is meant to handle all the rest cases. **However, for case 3, I can't reproduce the effect in the first place.** What I mean is explained by the following example:
```r
DT::datatable(
data.frame(a = 1, b = 2, c = 3, d = 4),
options = list(
columnDefs = list(
list(className = "dt_center", targets = "a") 
)
)
)
```
For 1, 2 and 4 cases, they are correctly handled now.
```r
DT::datatable(
data.frame(a = 1, b = 2, c = 3, d = 4),
options = list(
columnDefs = list(
list(className = "dt-center", targets = "_all")
)
)
)
DT::datatable(
data.frame(a = 1, b = 2, c = 3, d = 4),
options = list(
columnDefs = …
```
> classNameDefinedColumns() now identifies negative and "_all" targets

- DESCRIPTION
- NEWS.md
- R/datatables.R
Fix the issue that the first header is still right aligned when the data has no row name and the `target` is set to `"_all"`. It's a patch for #512 .
```r
DT::datatable(
data.frame(a = 1, b = 2, c = 3, d = 4),
options = list(
columnDefs = list(
list(className = "dt-center", targets = "_all")
)
)
)
DT::datatable(
data.frame(a = 1, b = 2, c = 3, d = 4),
options = list(
columnDefs = list(
list(className = "dt-center", targets = c(-1, 2))
)
)
)
DT::datatable(
sapply(iris[,1:3], as.integer),
options = list(
columnDefs = list(
list(className = "dt-center", targets = "_all")
)
)
)
DT::datatable(
iris[,1:3], rownames = FALSE,
options = list(
columnDefs = list(
list(className = "dt-center", targets = "_all")
)
)
)
```
> Fix the issue that the first header is still right aligned

- DESCRIPTION
- NEWS.md
- R/shiny.R
closes #496 
```r
library(shiny)
dat <- data.frame(
a = c(5, 6, NA, Inf, 10, 100),
b = c(letters[1:4], NA, NA),
c = factor(c(letters[1:4], NA, NA)),
stringsAsFactors = FALSE
)
shinyApp(
radioButtons("na_inf", "na_inf", c("null", "string"), inline = TRUE),
fluidRow(
column(
6,
h3("client mode"),
DT::dataTableOutput("client_dt")
),
column(
6,
h3("server mode"),
DT::dataTableOutput("server_dt")
)
)
),
server = function(input,output){
observe(
options("htmlwidgets.TOJSON_ARGS" = list(na = input$na_inf))
)
output$client_dt <- DT::renderDataTable({
input$na_inf
DT::datatable(head(dat))
}, server = FALSE)
output$server_dt <- DT::renderDataTable({
input$na_inf
DT::datatable(head(dat))
}, server = TRUE)
},
options = list(port = 6815)
)
```
> Respect htmlwidgets.TOJSON_ARGS in server-side processing mode

- DESCRIPTION
- NEWS.md
- R/format.R
- inst/htmlwidgets/datatables.js
Closes #241 
Improve the format of the filter of `Date` / `Datetime` columns. It will display the same format and timezone as the column content.
~~At the time of writing, the PR is unfinished because it doesn't work for server-side processing mode.~~ DONE, it now works properly with server-side processing mode.
```r
library(DT)
library(shiny)
df <- data.frame(
time = lubridate::ymd_hm(201801011000) + lubridate::dminutes(0:120),
time2 = lubridate::ymd_hm(201801011000) + lubridate::dminutes(0:120),
date = lubridate::ymd(20180101) + lubridate::ddays(0:120),
date2 = lubridate::ymd(20180101) + lubridate::ddays(0:120)
)
h3("server = TRUE"),
DT::DTOutput("tbl1"),
hr(),
h3("server = FALSE"),
DT::DTOutput("tbl2"),
hr(),
h3("without `formatDate()`"),
DT::DTOutput("tbl0")
)
server …
```
> Improve the format of the filter of `Date` / `Datetime` columns

- DESCRIPTION
- NEWS.md
- R/shiny.R
- inst/htmlwidgets/datatables.js
This PR fixes a bug that `selectRows()` and `selectColumns()` doesn't work (or works partially and inconsistently) for certain inputs, such as scalar inputs or character inputs (e.g., "3", "5").
You can try:
- select only one number and click __numeric submit__ and __string submit__ respectively.
- select only two or more numbers and click __numeric submit__ and __string submit__ respectively.
You will find that something like only the column gets selected or `tbl_selected_rows` gets updated (__be aware of the top line of the app where I put the text info__) but in the UI it's not.
```r
library(DT)
library(shiny)
textOutput("info"),
actionButton("clear", "clear all"),
inputPanel(
selectInput("rows_tbl", "rows", 1:10, multiple = TRUE),
selectInput("cols_tbl", "cols", 1:5, …
```
> fix selectRows/Columns()'s weird behavior for certain inputs

- DESCRIPTION
- NEWS.md
- R/shiny.R
Closes #525 
Some user wants to implement some heavy customized datatable style, such as in #525, a child table for each row. The current implement `cleanDataFrame()` doesn't support this and leads to a broken datatable in the server-side processing mode. This PR is going to fix this. 
- __Before this PR__ : The browser will throw an error says 
```
DataTables warning: table id=DataTables_Table_0 - Error in `[<-.data.frame`(`*tmp*`, , j, value = list(structure(list(A = c("A", : replacement element 1 is a matrix/data frame of 3 rows, need 2
```
- __After this PR__ : It works.
---
```r
library(data.table)
library(shiny)
library(DT)
dat <- local({
n <- 6
DT <- data.table(
HEADER = '&#9658;',
A = rep_len(LETTERS, n),
B = rep_len(1:10, n),
C = rep_len(c("GRP1", "GRP2"), n)
)
DT[, .(D=.(.SD)), …
```
> the server mode supports sub data.frame in its column now

- NEWS.md
- R/datatables.R
- R/shiny.R
Closes #533 
Ref to #513 #496 
Introduce a new option `DT.TOJSON_ARGS` to control the NA's printing value, mainly.  
**UPDATE** The default value on the server-side processing mode is set to `getOptions("DT.TOJSON_ARGS", getOptions("htmlwidgets.TOJSON_ARGS")` in order to preserve the same behavior as the client mode, on which `htmlwidgets` packages will pick up`htmlwidgets.TOJSON_ARGS` by default.
see https://github.com/ramnathv/htmlwidgets/blob/e3097fa5ff31402f7fce60f8a2e86147a9b983b2/R/utils.R#L31-L32
```r
library(shiny)
dat <- data.frame(
a = c(5, 6, NA, Inf, 10, 100),
b = c(letters[1:4], NA, NA),
c = factor(c(letters[1:4], NA, NA)),
stringsAsFactors = FALSE
)
shinyApp(
radioButtons("na_inf", "na_inf", c("no-option", "null", "string"), inline = TRUE), …
```
> introduce a new option DT.TOJSON_ARGS

- DESCRIPTION
- NEWS.md
- inst/htmlwidgets/datatables.js
Closes #538 
Fix the bug that `formatDate()` may display dates off by one day when method = "toLocaleDateString".
This PR is a patch for https://github.com/rstudio/DT/commit/3d8fa2479219d981c5a06f4dd31be358cc21a9aa ( The fix to https://github.com/rstudio/DT/issues/198)
However, it requires the timezone of you browser being set to UTC minus XXX like EST to reproduce.
```r
DT::datatable(data.frame(x="2018-01-01")) %>% formatDate('x', method="toLocaleDateString")
DT::datatable(data.frame(x=as.Date("2018-01-01"))) %>% formatDate('x', method="toLocaleDateString")
```
> `formatDate()` may display dates off by one day when method = "toLocaleDateString"

- DESCRIPTION
- NEWS.md
- R/utils.R
Closes #541 
`DT:::coerceValue()` should now throws warning for characters.
```r
DT:::coerceValue("a", "b")
#> Warning in DT:::coerceValue("a", "b"): The data type is not supported:
#> character
#> [1] "a"
packageVersion("DT")
#> [1] '0.4.10'
```
> `coerceValue()` no longer throws warnings for class `charactor`

- DESCRIPTION
- NEWS.md
- inst/htmlwidgets/datatables.js
closes #556 
In IE11, the scroll bar of the selectize input of the filter will disappear when you try to click it. This PR will fix this issue. 
The comment of the changed line says:
> an ugly hack to deal with shiny: for some reason, the onBlur event of selectize does not work in shiny
My example shows it works in shiny as well. Hopefully, I don't miss anything.
```r
library(DT)
df <- data.frame(a = LETTERS)
datatable(df, filter = 'top')
```
```r
library(shiny)
library(DT)
df <- data.frame(a = LETTERS)
ui <- basicPage(DT::DTOutput("dt"))
server <- function(input, output) {
output$dt <- DT::renderDT(df, filter = "top")
}
runApp(list(ui = ui, server = server))
```
> fix the scroll bar issue in IE11

- DESCRIPTION
- NEWS.md
- R/format.R
- man/styleInterval.Rd
Closes #546
Before this PR, you can't set the default css value for a column, even if you try to do it like below (I don't why...).
``` r
library(DT)
df <- data.frame(a = 0:9)
tmp <- datatable(df) %>%
DT::formatStyle("a", backgroundColor = styleEqual(0, "green")) %>%
DT::formatStyle("a", backgroundColor = "red")
cat(tmp$x$options$rowCallback)
#> function(row, data) {
#> var value=data[1]; $(this.api().cell(row, 1).node()).css({'background-color':'red'});
#> var value=data[1]; $(this.api().cell(row, 1).node()).css({'background-color':value == 0.000000 ? 'green' : ''});
#> }
tmp
```
Anyway, it makes sense to me to be able to set the default CSS value.
```r
library(DT)
df <- data.frame(a = 0:9)
datatable(df) %>%
DT::formatStyle("a", backgroundColor = styleEqual(0, "green", default = "red")) …
```
> add the param default for `styleEqual()`

- tools/update_DT.R
Closes #607 
It's strange that I can't use `download.file()` to fetch cdn.rawgit.com files, despite that I'm using a VPN... (I can use Safari to browser cdn.rawgit.com, though).
So I execute the update_DT.R and find no change in git, so it should be ok.
In addition, I notice some minor issues in update_DT.R:
- The RowReorder extension files will still be empty;
- Some directories need to be created in advance, otherwise it throws errors.
> Replace the rawgit.com URLs with raw.githubusercontent.com

- R/shiny.R
This small change allows for defining a custom filter function in `renderDataTable`.
Currently, the only possibility to set the custom filter function is `dataTableAjax`, it's more clear to set the filter function in `renderDataTable`.
>  Parameters to define custom filter function.

- NEWS.md
- R/shiny.R
- man/dataTableOutput.Rd
Closes #639 
#638 added a new param `filterFunc` to `renderDT()`. When users call it with the argument `filter`, it's `filterFunc` that being matched, thanks to R's partial matching... So, `filter` will never be passed to `...` and thus to `datatable()` unless `filterFunc` being provided at the same time.
There're two ways to fix this:
- Rename the `filterFunc` like `funcFilter`,
- [Add the `filter` param explicitly](https://github.com/rstudio/DT/compare/master...shrektan:fix639).
The first solution looks simpler and cleaner to me. 
```f
library(shiny)
library(DT)
ui <- fluidPage(DTOutput("dat"))
output$dat <- renderDT(mtcars[FALSE, ], filter = 'top')
}
shinyApp(ui, server)
```
> Rename filterFunc to funcFilter

- DESCRIPTION
- NEWS.md
- inst/htmlwidgets/datatables.js
Closes #645
Since `cell_edit` will only be triggered when the value shown on the table has been changed so it's almost always what user expects.
1. Run the app
1. Edit any cell to any value, e.g., cell(1,1) to "aaa" 
1. Click the button
1. Edit again with the same value "aaa"
Previously the reactive events won't be triggered. With this PR, it will.
```r
library(shiny)
library(DT)
shinyApp(
fluidRow(
verbatimTextOutput('edit_content'),
column(2, actionButton('refresh', 'Refresh Data', icon = icon('refresh'))),
column(10, DT::dataTableOutput('foo'))
)
),
loopData = reactive({
input$refresh
iris
})
output$foo = DT::renderDataTable(isolate(loopData()), editable = TRUE)
proxy = dataTableProxy('foo')
observe({
replaceData(proxy, …
```
> `cell_edit` now always triggers a reactive event on the R side

- R/datatables.R
- man/datatable.Rd
> Better doc on column indices provided in escape when using rownames

- DESCRIPTION
- NEWS.md
- R/format.R
Closes #666  also use %d when expecting integer. 
PS: Didn't notice #667 but I believe this way is more robust by taking advantage of jsonlite.
``` r
cat(DT:::jsValues(Sys.Date()))
#> "2019-07-11"
cat(DT:::jsValues(Sys.time()))
#> "2019-07-11T15:27:40Z"
cat(DT:::jsValues(1L:3L))
#> 1 2 3
cat(DT:::jsValues(c(1.0, 2.3)))
#> 1 2.3
cat(DT:::jsValues(letters[1:5]))
#> "a" "b" "c" "d" "e"
```
<sup>Created on 2019-07-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
```r
library(magrittr)
library(DT)
DT::datatable(data.frame(x = 1e5)) %>%
DT::formatRound("x", mark = "'")
options(OutDec=',')
datatable(iris) %>% 
formatStyle(1,color=styleInterval(c(4.9),c('green','red'))) %>%
formatStyle(2,color=styleEqual(c(3.1, 3.2),c('green','red'))) %>%
formatStyle(
'Petal.Length', …
```
> better jsValues() to convert R object to js values

- DESCRIPTION
- NEWS.md
- inst/htmlwidgets/datatables.js
Closes #554 
Not an elegant solution but maybe the only way that works. It looks harmless to me because the css attributes will be reverted back later.
Thanks @philibe for providing the css code.
```r
library(DT)
df <- do.call(data.frame, c(setNames(lapply(LETTERS, function(x) iris$Species), letters), list(stringsAsFactors = FALSE)))
datatable(df, filter = 'top', options = list(scrollX = "30%"))
```
> Filter boxes display in correct position when there're many columns

- DESCRIPTION
- NEWS.md
- R/format.R
- man/styleInterval.Rd
Closes #632 
Although the default value of `default` is changed, I believe the current default behavior (left the non-matched cells' CSS value unchanged) is almost always desired.
```r
library(DT)
myTable = datatable(
data.frame(V1 = c('a', 'b', 'c', 'd'), V2 = c('1', '2', '3', '4'))
)
myTable %>% formatStyle( 
'V1',
target = 'row',
backgroundColor = styleEqual('a', 'red')
) %>% formatStyle(
'V1',
target = 'row',
backgroundColor = styleEqual('c', 'green')
)
```
(Note the first row's color is blank, meaning it gets overridden by the 2nd `formatStyle()`)
(Works as expected)
> `formatStyle()` with `styleEqual()` is now chainable by default

- DESCRIPTION
- NEWS.md
- inst/htmlwidgets/datatables.js
Closes #705
When scrollX/Y is enabled, the column selection won't work in `row+column` mode. The reason is that the datatable library will seperate the footer from the body when there's a scroller. The old foot selector won't work somehow. This patch uses the datatables' api to select the footer, which should be robuster (at least ok for this case).
```r
library(shiny)
library(DT)
ui = basicPage(verbatimTextOutput('col_select'), DTOutput("tbl"))
output$tbl = DT::renderDT({
DT::datatable(
iris,
selection = list(mode = 'multiple', target = 'row+column'),
options = list(scrollX = TRUE, scrollY = "300px")
)
})
output$col_select = renderPrint({
input$tbl_columns_selected
})
}
shinyApp(ui = ui, server = server)
```
> Robuster footer selector when scrollX/Y is enabled

- DESCRIPTION
- NEWS.md
- R/format.R
Closes #723 
```r
library(DT)
tbl = data.frame(
A = c('a', 'b', '>a', "<b"),
B = c('red', 'green', 'yellow', 'pink'),
stringsAsFactors = FALSE
)
datatable(tbl) %>% 
formatStyle("A", target = "row", backgroundColor = styleEqual(tbl$A, tbl$B))
```
> need to compare the escaped levels for `styleEqual()`

- NEWS.md
- R/shiny.R
This PR is to extend the filtering by allowing extended regular expressions, which users will want to use for example to look ahead or behind, or to negate search terms.
> Use Perl REs in filters

- DESCRIPTION
- NEWS.md
- R/datatables.R
Closes #726 
Not sure why the available option was `sort(unique(d))` but I think `levels(d)` sounds better since it's a factor.
```r
library(DT)
datatable(data.frame(a = factor(c("a", "b"), levels = c("a", "b", "c"))), filter = 'top')
```
> should use levels() for factor column's filter

- DESCRIPTION
- R/shiny.R
- inst/examples/ajax-shiny.R
We noticed when testing [shinyloadtest](https://github.com/rstudio/shinyloadtest) that the shiny example [063-superzip-example](https://github.com/rstudio/shiny-examples/tree/master/063-superzip-example) didn't work.
It turned out the reason for the failure was non-determinism in the application. The example used `DT::dataTableAjax()` and [didn't supply an `outputId` parameter](https://github.com/rstudio/shiny-examples/blob/918cd7971353982e5f5256102b6b96a8a31959b5/063-superzip-example/server.R#L179), which caused DT to generate a random one using `tempfile()`.
We were able to fix the example by [simply specifying an outputId](https://github.com/rstudio/shiny-examples/pull/179), but it occurred to us that we could maybe prevent others from running into this problem by making a small …
> Use current outputId in dataTableAjax() if available

- .gitignore
- tools/update_DT.R
(The number of files changed should be only one after #735 gets merged)
Despite that with not-too-much efforts, this script can be fully automated (we can read the latest extension's version number and then generate the downloading URL), since we only update the library occasionally, I'm ok by clicking and download manually from datatables.net.
> Rewrite the javascript library updating script

- inst/examples/DT-scroller/server.R
From https://cdn.datatables.net/scroller/2.0.0/ we know that using `dom = 'S'` is deprecated after Scroller version 2.0.0 
> Note also that the option to initialise Scroller through the dom option (with the S feature) has been removed, and scroller should be used instead.
> should use scroller = TRUE to initialize Scroller extension

- R/datatables.R
- R/shiny.R
- man/datatable.Rd
Now I think we should only support the Select ext in the client-processing mode (see #717 for the reason).
So I'm going to split  three patches:
1. Be clear that we only recommend the Select ext is used in the client mode and the user should set `selection = 'none'`
1. Add the support of the Select ext - so that the rows/columns/cells_selected should get updated according to the selection
1. Further improvement on the current selection implementations like `shift` for cells and columns
And this is the first one.
Thanks.
> Warn if Select ext is used in server mode or with selection enabled

- DESCRIPTION
- NEWS.md
- inst/htmlwidgets/datatables.js
The Select extension on the client mode will now trigger the updating of the server-side values like rows/columns/cells_selected.
```r
library(shiny)
radioButtons('style', 'style', c('os', 'multi', 'single', 'multi+shift'), inline = TRUE),
radioButtons('items', 'items', c('row', 'column', 'cell'), inline = TRUE),
DT::DTOutput('tbl'),
verbatimTextOutput('print')
)
output$print = renderPrint({
print(input$tbl_rows_selected)
print(input$tbl_columns_selected)
print(input$tbl_cells_selected)
})
output$tbl = DT::renderDT(DT::datatable(
selection = 'none', 
iris, extensions = c('Select', 'Buttons'), options = list(
select = list(style = input$style, items = input$items),
dom = 'Blfrtip',
rowId = 0,
buttons = c('selectAll', 'selectNone', …
```
> Support Select ext for the client-side processing mode

- DESCRIPTION
- NEWS.md
- inst/htmlwidgets/lib/datatables-plugins/features/scrollResize/source.min.js
Closes #467 
See https://datatables.net/blog/2017-12-31 for more info about this plugin.
Try to resize the red area. With this plugin, the table will fit it well. Otherwise, it will be fixed to a certain height.
```r
library(shiny)
ui <- tags$html(
tags$head(
tags$link(
rel = "stylesheet", href = "//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"
),
tags$script(
src = "https://code.jquery.com/ui/1.12.1/jquery-ui.js"
),
tags$script(
DT::JS("$(function() {$('#resizable').resizable();});")
)
),
tags$body(
radioButtons('scrollresize', 'scrollresize', choices = c('TRUE', 'FALSE')),
div(
id = 'resizable',
style = 'height:500px;background-color:red;',
DT::DTOutput('tbl', height = '100%')
)
)
)
dat <- iris[1:50,]
output$tbl <- DT::renderDT(
if …
```
> add scrollResize plugin

- inst/htmlwidgets/lib/datatables/css/dataTables.bootstrap.extra.css
The selection color in bootstrap should be the same as the color of the page button.
The two colors are very close in fact but I guess the intention is to use the identical color.
> Tweak the selection color of bootstrap theme

- NEWS.md
- R/datatables.R
- inst/htmlwidgets/datatables.js
- inst/htmlwidgets/lib/datatables/css/dataTables.bootstrap4.extra.css
Closes #601
So that column alignment and selection style can be displayed correctly.
```r
library(shiny)
library(DT)
shinyApp(
ui = tagList(
tags$head(
tags$link(
rel="stylesheet",
href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css"
)
),
DT::dataTableOutput('tbl')
),
output$tbl = DT::renderDataTable(
iris, style = "bootstrap4", options = list(lengthChange = FALSE)
)
}
)
```
> Add Bootstrap4 extra css file

- DESCRIPTION
- NEWS.md
- R/format.R
- inst/htmlwidgets/datatables.js
Closes #776 
Except `formatStyle()`, all other formatting functions now call [column.render](https://datatables.net/reference/option/columns.render) option. By this way, other extensions (like the "Responsive" plugin) can be natively supported. 
The reason that `formatStyle()` still has to use `rowCallback` is it may use other columns' value and it changes the CSS style of the cell. Both seem not possible in `column.render`.
(**UPDATE** Using other values in the same row seems possible but changing the CSS style still not)
(**UPDATE2** It's also possible by hacking to change the CSS style but it still won't work for Responsive Plugin. So I'd rather keep the way it is. See https://github.com/rstudio/DT/issues/399#issuecomment-596184504)
```r
library(DT)
set.seed(100)
x = round(rnorm(10), …
```
> Use column.render option to implement formatXXX()

- DESCRIPTION
- NEWS.md
- R/shiny.R
Closes #152 
The left table doesn't react to the select input but the right table does.
Both two tables react the select input.
```r
library(shiny)
library(DT)
selectInput('length', "PageLength", c(1:10) * 10),
fluidRow(
column(width = 6L, DT::DTOutput('tbl1')),
column(width = 6L, DT::DTOutput('tbl2'))
)
)
output$tbl1 = DT::renderDT(iris, options = list(pageLength = input$length))
output$tbl2 = DT::renderDT(DT::datatable(iris, options = list(pageLength = input$length)))
}
shiny::runApp(list(ui = ui, server = server))
```
> renderDT() should react to `...` arguments

- NEWS.md
- R/format.R
Closes #623 
As discussed in #623, throwing errors when there're non-existing columns may not benefit much:
- If the non-existing column is not desired, the user will notice the error anyway;
- If it's desired, the user will be grateful if we just omit those columns as they are often generated in a dynamic way. Otherwise, the user has to write a verbose code to do that, considering there may be multiple chained formatting functions.
```r
library(DT)
dat = data.frame(A = 1:10, B = 1:10 / 10)
datatable(dat) %>% formatPercentage(c("B", "C"))
datatable(dat) %>% formatStyle(c("B", "C"), "B", color = "red")
datatable(dat) %>% formatStyle(c("B", "C"), "C", color = "red")
```
> formatting functions allow non-existing columns to be specified

- DESCRIPTION
- NEWS.md
- inst/htmlwidgets/datatables.js
Fixes #776 
Otherwise, the browser will display a warning box for all the NA elements.
```r
library(DT)
library(dplyr)
df_mtcars <- mtcars %>% 
mutate(
mpg_percents_visible = mpg / sum(mpg),
mpg_percents_hidden = mpg / sum(mpg)) %>% 
select(mpg_percents_visible, mpg_percents_hidden)
df_mtcars[2, ]$mpg_percents_hidden <- NA
x <- datatable(df_mtcars) %>% 
formatPercentage(c('mpg_percents_visible', 'mpg_percents_hidden'))
x
```
> DTWidget.formatxxx should return the empty string

- DESCRIPTION
- NEWS.md
- inst/htmlwidgets/css/datatables-crosstalk.css
Closes #563 
Because [`pkgdown` sets `table {display: block;}` in its CSS file](https://github.com/r-lib/pkgdown/blob/5e873fd9e478dddd784c31d8c8f994fd4b341c2a/inst/assets/pkgdown.css#L197-L200), DT will not be displayed correctly, as it prevents the table body from full-width spanning but not the search panel and the page buttons. 
I proposed this issue in upstream (https://github.com/DataTables/DataTablesSrc/issues/160#issuecomment-602692737) but it may not get fixed there. 
Adding this CSS in their Rmarkdown source file will fix this. However, it usually surprises the user and is difficult to track down the cause.
This fix should be safe in my opinion and considering the large users of both pkgdown and DT, I believe this PR is necessary.
```r
library(shiny)
tags$head( …
```
> fix the issue that DT doesn't look right in pkgdown

- DESCRIPTION
- NEWS.md
- R/format.R
- tests/testit/test-format.R
Closes #785 
When the users (usually new beginners) call formatting function on `DT::renderDT()`, incorrectly, the error message thrown is ambiguous, complaining the colnames unmatched.
Now it throws a clearer error message that "a table object created from datatable() was expected".
> formatting functions throw clearer error message when 1st arg is not expected

- NEWS.md
- R/format.R
- man/formatCurrency.Rd
- tests/testit/test-format.R
Closes #790 
I didn't notice that formatting functions support vectorized inputs when implementing PR #777. This PR fixes my mistakes.
Now the below code works.
```r
library(DT)
dat = data.frame(A = rnorm(1:10), B = rnorm(1:10))
datatable(dat) %>% formatRound(1:2, digits = 3:4)
```
> Formatting functions should support vectorized arguments

- R/shiny.R
Right now, the `server` argument in `renderDT()` doesn't react to the inputs in Shiny. This PR enables it.
It's trivial but I personally find it's very useful when testing.
```r
library(shiny)
ui = fluidPage(sidebarLayout(
sidebarPanel(
radioButtons('server','server',c('TRUE','FALSE'))
),
mainPanel(
DT::DTOutput('tbl')    
)
))
output$tbl = DT::renderDT({
tbl = data.frame(A = rnorm(10), B = rnorm(10))
}, server = as.logical(input$server))
}
shiny::runApp(list(ui = ui, server = server), port = 6435)
```
> make `renderDT(server=)` reactive in Shiny

- NEWS.md
- R/datatables.R
- tests/testit/test-datatables.R
If the users provide the param incorrectly, right now they can only see the error message in the browser's console, which is difficult for those who are not familiar with JS.
> validate the `selection` param on R side

- DESCRIPTION
- NEWS.md
- R/datatables.R
- R/shiny.R
- inst/examples/DT-selection/server.R
- inst/htmlwidgets/datatables.js
- man/datatable.Rd
- man/proxy.Rd
- tests/testit/test-datatables.R
Closes #201 
Closes #768 
1. the 0th column is the row name so our users usually want to "disable" the selection
1. even if somehow their real intention is to "enable", they can provide the column indices reversely, i.e., "disable" other columns. This is no difficult and no performance issues as the number of columns is usually very limited. 
See Details section in `DT::datatable`
> selectable could be NULL, TRUE, FALSE or indices, where NULL and TRUE mean all the table is selectable. When FALSE, it means users can't select the table by the cursor (but they could still be able to select the table via dataTableProxy). If indices, they must be all positive or non-positive values. All positive indices mean only the ranges are selectable while all non-positive indices mean the ranges are not …
> Be able to control the Selectable range

- inst/htmlwidgets/datatables.js
There is no built in method to update the slider and dropdown filters when data is replaced (#462), however, it is possible for these widgets to be updated using javascript.
In order for the slider to work correctly, the minimum and maximum values of the column need to be based on the endpoints of the slider, instead of hardcoded based on the initial data.
> Use the endpoints of the noUiSlider for filtering

- NEWS.md
- inst/htmlwidgets/datatables.js
This PR modifies the event listeners for `row_last_clicked` and `cell_clicked` events to always send the value of the clicked row or cell when clicked. Previously, the value was sent only if the clicked row had not changed.
The motivation for this is to be able to write `row_last_clicked` "event handlers" in shiny, for example adding or removing the last clicked row to the collection of selected rows when the data is being filtered using non-DT inputs elsewhere in the app.
Apologies for not first opening an issue, I thought it might be easier to just propose the changes.
<details><summary>Here's a small example app</summary>
```r
library(shiny)
library(DT)
library(dplyr)
tags$p("This is a simple demo, but the filtering UI could be much more complicated."), …
```
> Always send "_clicked" events

- DESCRIPTION
- NEWS.md
- R/format.R
Closes #837 
See the documentation at https://datatables.net/reference/option/columns.render (the function section)
```r
library(DT)
data <- data.frame(
VALUE = c(998, 999, 1000),
ORDER = 1:3
)
x <- DT::datatable(data, options = list(order = list(1, 'desc')) ) %>%
formatCurrency(c("VALUE","ORDER"),currency='',digits=0,mark=".",dec=",")
x
```
> Should apply the render functions only for the "display" purpose

- DESCRIPTION
- NEWS.md
- R/format.R
Fixes #843 
styleColorBar() now displays correctly on Safari when the data is greater than the upper limit (the css percentage value is negative)
Thanks @Seyphaton for the report and the solution!
```r
dt <- DT::datatable(data = mtcars, options = list(pageLength = -1))
dt <- DT::formatStyle(
dt, "mpg", background = styleColorBar(
data = c(0, max(mtcars$mpg * 0.5)), color = "blue"
)
)
dt
```
> styleColorBar() should handle out-of-range value properly

- NEWS.md
- inst/htmlwidgets/lib/datatables-plugins/filtering/accent-neutralise/source.js
- tools/update_DT.R
Closes #822
```r
DT::datatable(data.frame(A = c('a', 'u', 'ü', 'b'), B = 1:4), plugins = 'accent-neutralise')
```
> add a new plugin "accent-neutralise"

- DESCRIPTION
- NEWS.md
- R/shiny.R
- inst/htmlwidgets/datatables.js
- man/proxy.Rd
Fixes #853 
`addRow()` now has a new parameter `resetPaging`, which can be used to control whether the page should be reset after the row gets added.
```r
library(shiny)
library(DT)
output$foo = DT::renderDataTable(
head(iris, 20), server = FALSE,
caption = 'Using a proxy object to manipulate the table',
options = if (input$paging == "FALSE") list(
pageLength=-1,
scrollY = "200px",
bPaginate = FALSE
) else list()
)
proxy = dataTableProxy('foo')
observeEvent(input$add, {
proxy %>% addRow(iris[sample(nrow(iris), 1), , drop = FALSE], input$resetPaging == "TRUE")
})
}
sidebarLayout(
sidebarPanel(
radioButtons('paging', "Paging", c('TRUE', 'FALSE')),
radioButtons('resetPaging', "Reset Paging", c('TRUE', 'FALSE')), …
```
> `addRow()` now has a new parameter `resetPaging`

- DESCRIPTION
- NEWS.md
- R/datatables.R
- tests/testit/test-datatables.R
Fix #806 
I think leaving irrelevant classes as they are is harmless. It's usually what users expect, in my opinion.
> DT2BSClass() should keep unknown classes unchanged

- DESCRIPTION
- NEWS.md
- R/datatables.R
- tests/testit/test-datatables.R
Fixes #848
Due to the fact that `fixServerOptions()` uses the sub-element's value of options$search,
https://github.com/rstudio/DT/blob/ddd608e270528313eb9edf8fd8af5bc3bc4c91cd/R/shiny.R#L729-L738
the following code throw unhelpful message:
```r
shiny::shinyApp(
ui = shiny::fluidPage(DT::DTOutput("my_dt")),
output$my_dt <- DT::renderDT({
DT::datatable(data = mtcars[1:3, 1:2],
options = list(search = TRUE))
})
}
)
```
```
$ operator is invalid for atomic vectors
```
```
The value of `search` in `options` must be NULL or a list
```
> throw a clear message if options$search's value is illegal

- DESCRIPTION
- NEWS.md
- R/datatables.R
- R/shiny.R
- inst/htmlwidgets/datatables.js
- man/datatable.Rd
- tests/testit/test-datatables.R
Closes #856
1. `autoHideNavigation` now works with the default theme (previously, it only support the bootstrap theme)
1. The prerequisite (pageLength option + client-side mode) is properly documented
1. Throw warnings if pageLength option is not set or under server-side mode
```r
DT::datatable(head(iris, 10), options = list(pageLength = 15), autoHideNavigation = TRUE)
```
```r
library(shiny)
library(DT)
DTOutput("tbl")
)
server <- function(input, output) {
output$tbl = renderDT({
datatable(
head(iris, 10),
style = "bootstrap",
autoHideNavigation = TRUE,
options = list(pageLength = 20)
)
}, server = FALSE)
}
shiny::runApp(mget(c("ui", "server")))
```
> autoHideNavigation works with default theme and the doc is improved

- DESCRIPTION
- R/shiny.R
- man/dataTableOutput.Rd
With this simple example app, the first user will see a delay before it shows the table, but other users who visit the app should see it instantly.
```
library(shiny)
library(DT)
shinyApp(
ui = fluidPage(DTOutput('tbl')),
output$tbl <- renderDT({
message("Computing...")
Sys.sleep(2)
iris
}, 
server = FALSE, 
options = list(lengthChange = FALSE)
) %>%
bindCache(1)
}
)
```
> Add support for shiny::bindCache()

- NEWS.md
- R/datatables.R
Tiny change to allow passing responsive options like child row control and others: https://datatables.net/extensions/responsive/examples/child-rows/right-column.html 
Previously these would be overwritten by defaults when `options$responsive` set to `TRUE`.
Thanks heaps!
Hayden
> Don't overwrite responsive details/options if provided

- DESCRIPTION
- NEWS.md
- inst/htmlwidgets/datatables.js
Fixes #888
Before the PR, the example code won't work for `init_data == "zero"` but ok for `init_data == "one"`.
After the PR, both cases would work fine.
```r
library(shiny)
zero_row_data <- data.frame(
A = character(), B = character(),
stringsAsFactors = FALSE
)
one_row_data <- data.frame(
A = "A", B = "B",
stringsAsFactors = FALSE
)
radioButtons("init_data", "initial data", c("zero", "one"), inline = TRUE),
DT::DTOutput("tbl"), actionButton("add", "Add")
)
output$tbl <- DT::renderDT(
server = FALSE,
DT::datatable(if (input$init_data=="zero") zero_row_data else one_row_data)
)
proxy = DT::dataTableProxy(outputId = "tbl")
observeEvent(
input$add, {
DT::addRow(proxy, one_row_data)
}
)
}
shiny::runApp(mget(c("ui", "server"))) …
```
> addRow() works for zero-row DT table

- DESCRIPTION
- NEWS.md
- inst/htmlwidgets/lib/datatables-plugins/filtering/diacritics-neutralise/source.js
In short, this plugin provides additional support for filtering on special, _non-Latin_ characters — beyond what's supported in the [`accent-neutralise.js` plugin](https://github.com/rstudio/DT/issues/822). More information is located [on the DataTables website here](https://datatables.net/plug-ins/filtering/type-based/diacritics-neutralise).
Changes were modeled after #845.
> Add support for diacritics-neutralise.js plugin

- NEWS.md
- R/utils.R
- man/editData.Rd
Fixes #865 
```r
library(shiny)
library(DT) 
tbl = data.frame(
A = letters, B = LETTERS, stringsAsFactors = TRUE
)
DTOutput("tbl")
)
output$tbl = renderDT(tbl, editable = TRUE, rownames = TRUE)
proxy = dataTableProxy('tbl')
observeEvent(input$tbl_cell_edit, {
info = input$tbl_cell_edit
tbl <<- editData(tbl, info, proxy = proxy, resetPaging = FALSE, rownames = TRUE)
})
}
shinyApp(ui = ui, server = server)
```
**NOTE, the data.frame's columns are factors**
When editing table with new factor levels, DT displays the new value as NA, with a warning.
Now it displays as expected
> editData() would update factor levels when necessary

- NEWS.md
- inst/htmlwidgets/datatables.js
Closes #903
When statically rendered, DT's JS code executes before FlexDashboard has initialized, and so `isFillPage()` incorrectly returns false in that case. Also, `flexdashboard::flex_dashboard()` already sets the `options(DT.fillContainer = TRUE)` so this code seems unnecessary (it doesn't seem that the `paging = true` is needed either considering that [its the default in datatables.js](https://datatables.net/reference/option/paging)?)
> Don't use FlexDashboard.isFillPage() to override options client-side

- .github/workflows/R-CMD-check.yaml
- .github/workflows/test-coverage.yaml
Mainly because ubuntu 16.04 is deprecated
https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/
Using last version of `r-lib/actions/examples` workflow
> Update GHA workflow

- R/utils.R
- man/editData.Rd
This PR adresses #941 issue.
For parameter `info` (in `editData()` function) documentation indicated that returning object is a `data.frame` with columns: `row`, `column`, `value`, but second name should be `col`. This is problematic for the user, because when she / he refers to `object$column` (instead of `object$col`), `NULL` is returned.
> Documentation for editData changed for parameter info

- DESCRIPTION
- NEWS.md
- R/format.R
- inst/htmlwidgets/datatables.js
- man/formatCurrency.Rd
- tests/testit/test-format.R
Closes #953 
```r
set.seed(1106)
sample_data <- cbind(PCT = rnorm(10), CRY = rnorm(10) * 10000, SIG = rnorm(10) * 10000, RND = rnorm(10) * 10000)
sample_data <- rbind(0, sample_data)
htmltools::browsable(htmltools::withTags(htmltools::tagList(
h1("With zero.print"),
hr(),
DT::datatable(sample_data, selection = "none") |> 
formatPercentage("PCT", zero.print = "-") |>
formatCurrency("CRY", zero.print = "$$$$$$") |>
formatSignif("SIG", zero.print = "000e0000") |>
formatRound("RND", zero.print = "0000.000"),
h1("Without zero.print"),
hr(),
DT::datatable(sample_data, selection = "none") |> 
formatPercentage("PCT") |>
formatCurrency("CRY") |>
formatSignif("SIG") |>
formatRound("RND")
)))
```
> add zero.print to formatXXX functions

- DESCRIPTION
- NEWS.md
- R/datatables.R
- man/dataTableOutput.Rd
- man/datatable.Rd
- tests/testit/test-datatables.R
Due to implentation of DT, `options$columnDefs$targets` doesn't support string values (See #512). 
It's inconvinient as using column-names is always easier. In addition, it confuses the user in the first place, as it is inconsistent with DataTables' documentation.
This PR addresses this issue by converting the string valued `targets` into column index values of the data, internally.
```r
x <- rnorm(10)
rk <- rank(x)
prefix <- sample(LETTERS[1:3], replace = TRUE, 10)
x_txt <- sprintf("%s%0.2f%%", prefix, x * 100)
tbl <- data.frame(V1 = x, V2 = x_txt, V3 = x, RK = rk)
DT::datatable(tbl, options = list(
scrollY=FALSE, 
columnDefs = list(
list(visible = FALSE, targets = list("V3", 2))
)
))
```
> Allow string options$columnDefs$targets

- DESCRIPTION
- NEWS.md
- R/format.R
- man/styleInterval.Rd
- tests/testit/test-format.R
Closes #955 
```r
DT::datatable(
data.frame(A = letters, B = LETTERS)
) |> 
DT::formatStyle("A", backgroundColor = styleRow(2:4, "pink")) |>
DT::formatStyle("B", backgroundColor = styleEqual(c("C", "D"), "lightblue"))
```
> repeat the scalar values argument in `styleRow()` and `styleEqual()`

- DESCRIPTION
- NEWS.md
- R/shiny.R
Closes #959 
This is due to the change in R 3.4.0
```r
library(shiny)
actionButton("add", "Add Row"),
DT::DTOutput("tbl")
)
sample_row <- function() {
row <- sample(letters, 1L)
a <- sample(0:9, 1L)
b <- sample(letters, 3) |> paste0(collapse = "")
list(row, A = a, B = b)
}
df <- rbind(
"a" = c("A" = 1L, "B" = "abc"),
"b" = c("A" = 2L, "B" = "bcd")
)
output$tbl <- DT::renderDT({
df
}, server = FALSE)
proxy <- DT::dataTableProxy("tbl")
observeEvent(input$add, {
DT::addRow(proxy, sample_row())
})
}
shiny::runApp(mget(c("ui", "server")))
```
> fix addRow's support on a list of data

- NEWS.md
- R/shiny.R
Closes #965
Related to #963
Note, I confirm that `shiny::parseQueryString()` will mark the string result to UTF-8 on Windows.
> DT parses ajax request correctly

- DESCRIPTION
- NEWS.md
- inst/htmlwidgets/datatables.js
Fixes #951 
More info on this issue please see https://github.com/rstudio/DT/issues/951#issuecomment-1026464509
```r
DT::datatable(iris)
```
``````rmd
---
title: "RMarkdown Document"
output: flexdashboard::flex_dashboard
---
```{r table}
library(DT)
library(flexdashboard)
data.frame(x = 1:100) |> datatable()
```
``````
> Fix the bug that DT table can't vertically fill the container

- NEWS.md
- R/format.R
- man/formatCurrency.Rd
- man/styleInterval.Rd
Closes #520
```r
library(shiny)
library(DT)
data <- iris
data$DATE <- sample(0:500, replace = TRUE, size = nrow(data)) + as.Date("1990-01-01")
rowsOpt = list("top3and12" = c(1:3, 12), "1/5/12/20" = c(1,5,12,20), "all" = NULL)
radioButtons("rows", "rows", names(rowsOpt), inline = TRUE),
radioButtons("fmtfun", "format function", c(
"formatCurrency", "formatDate", "formatPercentage", "formatRound", "formatSignif", "formatString"
), inline = TRUE),
selectInput("cols", "columns", seq_len(ncol(data)), selected = c(1,3,6), multiple = TRUE),
DTOutput("tbl")
)
output$tbl = renderDT({
styler = function(data) {
args = list(
columns = as.integer(input$cols |> req()), rows = rowsOpt[[input$rows]]
)
if (input$fmtfun == "formatString") {
args = …
```
> Be able to specify the styled rows in `formatXXX()`

- R/shiny.R
Part of #971.
If `updateFilters()` sets tries to set new limits for a select filter that would have length 1, the data in the update message gets unboxed into a scalar. However, the JS code that accesses these values expects the message to always contain only arrays.
> Fix updating filters with length 1 limits

- R/shiny.R
Part of #971.
`updateFilter()` should apply new limits consistently with how they would appear if fully re-rendered (and thus calculated internally with `filterRow()`). Currently booleans always show all options, and `NA` if there are any, while factors let you pick from their levels, regardless of whether or not they are present in the data:
https://github.com/rstudio/DT/blob/815872d67141bb053ed9defd6b72cbaed2aa6668/R/datatables.R#L684-L692
This PR changes the new limits for factors and booleans calculated by `updateFilter()` to match those found by `filterRow()`.
> Update factors and logicals consistently with initial render

- DESCRIPTION
- NEWS.md
- R/shiny.R
- inst/examples/DT-updateFilters/DESCRIPTION
- inst/examples/DT-updateFilters/README.md
- inst/examples/DT-updateFilters/app.R
- inst/htmlwidgets/datatables.js
Part of #971.
This PR allows integer and character columns to be included in the data whose filters are being updated.
I also added an example app to demonstrate (and test) `updateFilters()`.
> Allow integer and character columns in `updateFilters()`

- NEWS.md
- R/datatables.R
- R/shiny.R
- inst/examples/DT-updateFilters/app.R
- inst/htmlwidgets/datatables.js
Part of #971.
This PR factors out the filter property calculations (like limits and disabled status) from `filterRow()`  into a new `columnFilters()` method. That common method is then used for both the initial render, and subsequent updates with `updateFilters()`, ensuring consistency.
As it flowed naturally into the above changes, I also updated the JS side for `updateFilters()` to also manage the enabled/disabled state of the controls.
There's a bit more going on in this PR, but I tried to group my commits sensibly. Hopefully that helps with review.
> Refactor `filterRow()` and update disabled state in `updateFilters()`

- inst/examples/DT-updateFilters/app.R
- inst/htmlwidgets/datatables.js
Closes #971.
- Fixed an issue where updating filters was writing to instead of reading the `searchable` status of the filter when determining whether or not they should be disabled. This was introduced in #977 so hasn't made it into "newsworthy" status yet.
- Added an example of missing values in sliders to the demo app.
- Some minor stylistic changes to better fit the code-base style.
> Fix `updateFilters()` with un-searchable columns

- NEWS.md
- R/shiny.R
- tests/testit/test-search.R
While working on #982 I thought of two optimizations to speed up server-side searching. This PR:
1. Doesn't bother searching rows that have already been ruled out by earlier searches.
2. Does the (much more expensive) global search after the (quicker) column searches have already been applied.
I also added some infrastructure to help test the server-side search handler `dataTablesFilter()`.
Benchmarking, I saw a ~20x speed improvement for a 340k x 6 dataset with a global search and two fairly specific column filters:
``` r
library(nycflights13)
flights0 <- flights[c("year", "month", "day", "carrier", "flight", "tailnum")]
flights0 <- as.data.frame(flights0)
query = list(
draw = "0", start = "0", length = "10", escape = "true",
search = list(
value = "N6", regex = "false", caseInsensitive …
```
> Server-side search optimizations

- NEWS.md
- inst/htmlwidgets/datatables.js
Tested with the Shiny app provided by @tverbeke in https://github.com/rstudio/DT/issues/1000
> fixed #1000 (rendering of missing numeric values)

- NEWS.md
- R/shiny.R
- inst/htmlwidgets/css/datatables.css
- inst/htmlwidgets/datatables.yaml
- man/dataTableOutput.Rd
See https://github.com/ramnathv/htmlwidgets/pull/437 for more details and motivation for these changes.
> dataTableOutput()'s width and height now default to NULL 

- NEWS.md
- inst/htmlwidgets/datatables.js
Changed `valueNew != value` to `valueNew !== value`. Fixes #1038
> exact comparison of valueNew and value

- DESCRIPTION
- NEWS.md
- R/shiny.R
- tests/testit/test-search.R
Fixes #1044.
I added tibble as a Suggested package in order to add a regression test. Would there be a better way to keep a regression test, and avoid adding the dependency?
> Fix `doGlobalSearch()` with tibbles

- DESCRIPTION
- NEWS.md
- R/datatables.R
Currently, when using a Bootstrap 5 theme from bslib and `style="auto"`, `datatable()` will use `"bootstrap4"` for the style. This results in a somewhat incorrectly styled datatable.
This PR improves the logic to use latest DT-supported Bootstrap styles corresponding to the current bslib theme. In this formulation, future Bootstrap updates would require updating this logic (so I left a todo comment), but if there's an easy way to list the bootstrap versions suppported by DT I could update the PR so that this part doesn't need to be updated when future BS versions are added.
> Support Bootstrap 5 with `datatable(style = "auto")`

- NEWS.md
- R/datatables.R
This PR seeks to bring support for a list of classes in `DT2BSClass()`, with the end goal of fixing the issue #1052.
In more details, when you select `style='bootstrap'`, `DT::datatable()` tries to translate the `class` argument, to a css rule with all the Bootstrap classes that were mentioned in the `class` argument. To make this translation, the `DT2BSClass()` function is called with the class argument. However, the `DT2BSClass()` function only supports a character vector as input.
This PR will allow `DT2BSClass()` to receive a list of booleans as input, as mentioned in the example from issue #1052.
```r
DT::datatable(mtcars, class=list(stripe=F), style = "bootstrap")
DT::datatable(mtcars, class=list(stripe=T, compact=F, hover=T), style = "bootstrap")
```
In essence, we use …
> Add support for list of classes in `DT2BSClass`

- NEWS.md
- inst/htmlwidgets/datatables.js
Fix disabling selection on hyperlink click, it is currently not working.
Selection is triggered by `mousedown`, so disabling selection on hyperlink click should also use the `mousedown` event.
> Fix disabling selection on hyperlink click

- NEWS.md
- R/datatables.R
- R/shiny.R
- inst/htmlwidgets/datatables.js
- tests/testit/test-sort.R
The re-ordered column order isn't sent server-side, so have added the column names to the DT options. This gets passed into the server-side parameters in `columns$[[col_id]]$name` (adding it to `data` instead caused errors)
This PR should resolve #534 , #921 and #1069
> Bugfix: Correctly sort re-ordered columns

- DESCRIPTION
- NEWS.md
- inst/htmlwidgets/datatables.js
Fixes #1110.
``` r
library(shiny)
library(DT)
actionButton("set_search", "Set column search"),
tags$hr(),
DTOutput("iris")
)
output$iris <- renderDT(
datatable(iris, filter = "top")
)
proxy <- dataTableProxy("iris")
observeEvent(input$set_search, {
updateSearch(proxy, keywords = list(columns = c("", "5.0 ... 6.0")))
})
}
shinyApp(ui, server)
```
> Update numeric slider values on updateSearch

- R/searchbuilder.R
- R/shiny.R
- tests/testit/test-searchbuilder.R
Follow-up to #1113.
Sometimes the client will send SearchBuilder queries that contain incomplete or invalid search criteria. For example, when the user changes the `data` that an existing criteria applies to, a search will be sent to the server with the `condition` component missing. In client-side processing, such invalid criteria are ignored.
This PR aligns server-side processing with the client-side implementation, by returning `NULL` to signal that a condition is invalid and should be ignored or that the search contains no valid criteria.
> Ignore invalid criteria in SearchBuilder server-side processing

- NEWS.md
- inst/htmlwidgets/datatables.js
Fixes #998.
Apply preset `searchCols` consistently by triggering `input` and `trigger`, just like with `updateSearch` in #1111.
> Always update filter widgets with preset `searchCols`

- NEWS.md
- inst/htmlwidgets/datatables.js
Fixes #247.
The `format*` functions append new `columnDefs` entries with customized renderer functions to apply column formatting. The idea in this PR is to fetch those same renderer functions to apply to filter slider labels.
``` r
DT::datatable(
tibble::tibble(
goal_completion = round(runif(10), 2),
bonus = goal_completion * 15:24 * 1000,
payday = Sys.Date() + 1:10
),
filter = "top"
) |>
DT::formatPercentage(1) |>
DT::formatCurrency(2) |>
DT::formatDate(3)
```
> Apply column formats to slider labels

- NEWS.md
- inst/htmlwidgets/datatables.js
> Maintain RowGroup dataSrc when moved with ColReorder

- DESCRIPTION
- NEWS.md
- R/datatables.R
- inst/htmlwidgets/datatables.js
- man/datatable.Rd
Closes #1072, closes #1083.
This PR adds support to use the `filter` parameter in `datatable()` to pass configuration directly to filter widget initialization in JavaScript. This is done by specifying a `$settings` element in the list form of the `filter` parameter, which itself is a named list with `$select` and `$slider` elements for select and slider widget configuration, respectively.
Example usage:
``` r
DT::datatable(
data.frame(
foo = factor(LETTERS, levels = sample(LETTERS)),
bar = rnorm(seq_along(LETTERS)) |> round(3)
),
filter = list(
position = "top",
settings = list(
select = list(
sortField = list(field = "text", direction = "desc")
),
slider = list(
orientation = "vertical"
)
)
)
)
```
> Add way to pass configuration to Selectize and noUiSlider widgets

- R/format.R
- inst/htmlwidgets/datatables.js
Follow-up to #1119.
This PR removes the now-unnecessary special-casing from `formatDate()` as the mechanism from #1119 handles it directly.
This also fixes a regression introduced in #1119 for datetime columns, which was caused by me overlooking to handle datetime values when applying a renderer to format the slider range labels.
There's some duplicated logic in the JS side `formatDate()` helper and `restore()`. I thought about refactoring that, but it would be a slightly more involved operation without a big direct benefit, so I decided not to mess with it at this point.
I tested manually with this app:
``` r
DT::datatable(
data.frame(
date = Sys.Date() + 1:10,
time = Sys.time() + 1:10 * 60 * 60 * 24
),
filter = "top"
) |> DT::formatDate(1:2, "toLocaleString")
```
> Remove special-casing of dates for slider formatting and fix datetimes

- NEWS.md
- R/shiny.R
- man/dataTableOutput.Rd
We're transitioning toward removing `shiny::dataTableOutput` and `shiny::renderDataTable` and having them shim their DT equivalents. (see https://github.com/rstudio/shiny/issues/3986)
Neither the addition of `outputArgs` nor the removal of the `@inheritParams` are urgently needed, just thought I'd do this while I was thinking of it.
> Add renderDT(outputArgs=), remove doc dependency on deprecated Shiny funcs

- NEWS.md
- R/shiny.R
> Always evaluate `renderDT()`'s `...` in the `parent.frame()`

- NEWS.md
- inst/htmlwidgets/datatables.js
This is "minimally invasive". After the reload of the table on the client and potentially restoring selections via JS callback function, the `cleanSelectedValues()` function sends potentially incorrect `<tbl>_xxx_selected` information to R. The patch uses the functions already implemented to send row/col/cell selections made via Select extension to R. It simply triggers one update right then and there. Since the messages get merged, this effectively overwrites the false message created by cleanSelectedValues() exactly when the bug #1125 is triggered. It may not be a complete fix for other scenarios, but it is brief and has minimal chance of breaking things for other use cases.
> fix selection sync on client mode update (fixes #1125)
